name: "Validate"
description: "Validates the pull request."
author: "Leonardo Montini"

inputs:
  gh-token:
    description: "The GitHub token for authentication."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
