name: Run my action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnp/pnp-sample-validation@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
